/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/base.glb --transform 
Files: src/assets/models/base.glb [2.4MB] > /Users/federicomartin/Desktop/Programación/ilikeit/mindar-r3f-image-tracking/base-transformed.glb [70.48KB] (97%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import baseModelURL from "../../assets/models/base-transformed.glb";

export function Base(props) {
	const { nodes, materials } = useGLTF(baseModelURL);
	return (
		<group {...props} dispose={null}>
			{/*<mesh geometry={nodes.btn_der.geometry} material={materials.Ui} />*/}
			{/*<mesh geometry={nodes.btn_izq.geometry} material={materials.Ui} />*/}
			<mesh geometry={nodes.btn_medio.geometry} material={materials.Ui} />
			<mesh geometry={nodes.plato.geometry} material={materials.Ui} />
		</group>
	);
}

useGLTF.preload(baseModelURL);
