/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/coffee.glb --transform 
Files: src/assets/models/coffee.glb [2.57MB] > /Users/federicomartin/Desktop/Programación/ilikeit/mindar-r3f-image-tracking/coffee-transformed.glb [33.66KB] (99%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import coffeeModelURL from "../../assets/models/coffee-transformed.glb";

export function Coffee(props) {
	const { nodes, materials } = useGLTF(coffeeModelURL);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Vaso_de_cafe.geometry}
				material={materials.Vaso}
			/>
		</group>
	);
}

useGLTF.preload(coffeeModelURL);
