/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/croissant.glb --transform 
Files: src/assets/models/croissant.glb [8.96MB] > /Users/federicomartin/Desktop/Programación/ilikeit/mindar-r3f-image-tracking/croissant-transformed.glb [332.83KB] (96%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import croissantModelURL from "../../assets/models/croissant-transformed.glb";

export function Croissant(props) {
	const { nodes, materials } = useGLTF(croissantModelURL);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Croissant.geometry}
				material={materials["Material_0.004"]}
			/>
		</group>
	);
}

useGLTF.preload(croissantModelURL);
